services:
  - type: web
    name: nba-analytics-dashboard
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main
